---
- name: "UI Folder | Set application destination folder"
  set_fact:
    ui_folder_destination_path: "{{ service_root_folder }}/{{ service_name | upper }}/{{ service_version }}/UI"

- import_tasks: unzip_files.yml
  when: >
        ui_folder_path is defined and
        ui_folder_path|length > 0
  notify:
      - "Unzip files"

- name: "UI Folder | Copy UI Folder"
  copy:
    src: "{{ ui_folder_path }}"
    dest: "{{ ui_folder_destination_path }}"
    owner: "{{ service_user }}"
    group: "{{ service_user_group }}"
    mode: 0500
  when: >
        ui_folder_path is defined and
        ui_folder_path|length > 0
  notify:
    - "Restart application"