---
- name: "UI Folder | Set application destination folder"
  set_fact:
    ui_folder_destination_path: "{{ service_artifact_destination_folder }}/ui"

- name: "UI Folder | Ensure ui folder exist"
  file:
    path: "{{ ui_folder_destination_path }}"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_user_group }}"
  become: true
  notify:
        - "Restart applicationt"

- name: "UI Folder | Ensure extractor presents"
  ansible.builtin.apt:
    name:
       - unzip
       -  tar
    state: present
  become: true

- name: "UI Folder | Extract archive"
  ansible.builtin.unarchive:
      src:  "{{ ui_compressed_path }}"
      dest:  "{{ ui_folder_destination_path }}"
  when: >
      ui_compressed_path is defined and
      ui_compressed_path|length > 0
  notify:
      - "Restart application"